@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InBsYXllciIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTczNzM4OTIwMCwiZXhwIjoxNzM3NDEwODAwfQ.8t0UUF_RJ7N3ORw1DuXL5byH6OgcMj6J5QSgBwpLTzg
@crateId = 2

### Fetch All Crates
GET http://localhost:8080/crates
Authorization: Bearer {{token}}

### Fetch Specific Crate by ID
GET http://localhost:8080/crates/id/{{crateId}}
Authorization: Bearer {{token}}

### Fetch all user crates
GET http://localhost:8080/crates/user/2
Authorization: Bearer {{token}}

### Create a New Crate
POST http://localhost:8080/crates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "crateAssetID": "wooden_crate",
  "patternIndex": 700,
  "ownerID": 2
}

